[package]
name = "xlsxgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "xlsxgen"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
chrono = "0.4.9"
quick-xml = "0.30.0"
